services:
  postgres:
    image: 'postgres:15.3'
    environment:
      - 'POSTGRES_DB=db_cars'
      - 'POSTGRES_PASSWORD=Test123'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'
    expose:
      - '5432'